### PR TITLE
Update it-IT.json

### PR DESCRIPTION
**Pull request by elvendork323**
Discord handle: @elvendork323#7890.

### CODE REVIEW

**Comment by tt2468** [comment]
Any chance you have time to finish more of the strings?

**Comment by elvendork323** [comment]
Yes! I'll work on some more this week, I just wanted to get the first ones on there and started.Sent via the Samsung Galaxy S8 Active, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: tt2468 <notifications@github.com> Date: 1/5/21  18:04  (GMT-06:00) To: tt2468/counting-translations <counting-translations@noreply.github.com> Cc: elvendork323 <sarahbuckley0323@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [tt2468/counting-translations] Update it-IT.json (#9) 
Any chance you have time to finish more of the strings?

**Comment by tt2468** [comment]
Converting this to a draft until it is done.

**Comment by tt2468** [comment]
Update: Ported your progress into crowdin. Refer to the updated README for finishing the strings. Closing this now, for updating the help message or bool substitutions, open a new pull request. Sorry for the complication!

**Pull request closed without merging**
